AllCops:
  TargetRubyVersion: 2.4.4

Style/RegexpLiteral:
  EnforcedStyle: slashes
  AllowInnerSlashes: true

Style/Documentation:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true
  EnforcedStyle: no_space

Metrics/LineLength:
  Enabled: True
  Max: 100

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*
