name: Ruby
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['3.4', '3.0', '2.7']
    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Build and test with Rake
        run: |
          gem install bundler undercover --no-doc
          bundle install --jobs 4 --retry 3
          bundle exec rake
          git fetch origin master:master
          undercover --compare master
